name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'npm'
        cache-dependency-path: |
          package.json
          package-lock.json
    - run: npm ci
    - run: npm test
    - run: npm run pkg
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pkg/*


