name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'npm'
        cache-dependency-path: |
          package.json
          package-lock.json
    - run: npm ci
    - run: npm test
    - name: Setup ldid
      uses: MOZGIII/install-ldid-action@v1
      with:
        tag: v2.1.5-procursus6
    - name: Setup QEMU/binfmt
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Build executable files
      run: npm run pkg
    - name: Cache executable files built
      uses: actions/cache/save@v3
      with:
        path: pkg
        key: ${{ github.run_id }}-${{ github.run_number }}
  goreleaser:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/goreleaser/goreleaser/issues/1715#issuecomment-667002748
      - run: |
          sudo snap install --classic snapcraft
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Restore cached executable files previously built
        uses: actions/cache/restore@v3
        with:
          path: pkg
          key: ${{ github.run_id }}-${{ github.run_number }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: false
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_PAT }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
